### PR TITLE
Linting rules

### PR DESCRIPTION
**Pull request by goremikins**
## Description
Improve linting rules to avoid common errors.

## Type of change
Please delete options that are not relevant.

- [X] Configuration update

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by goremikins** [comment]
@Theeraphat-Sorasetsakul , @dtanp-rft could you please (plan to) fix the associated linting errors to ensure:
1) There are no `==` assertions, so instead of `x == null` we should use `x === null || x === undefined`
2) space always follows a statement, e.g. `if (condition)` instead of `if(condition)`

**Comment by dtanp-rft** [comment]
Done. Also, new handy scripts added.

```
    "lint-fix": "node cli lint:fix",
    "lint-fix:all": "lerna run lint:fix"
```

**Review by Theeraphat-Sorasetsakul — APPROVED** [review]
Look good to add the rule. Lint and test is passed except warning: no-unused-vars on line 778 of packages/elements/src/number-field/index.ts . Should we fix this?

**Comment by goremikins** [comment]
Looks good to me

**Pull request merged**
