### PR TITLE
fix(list): `selectItem()` should always require a param

### PR DESCRIPTION
**Pull request by wsuwt**
## Description

`selectItem()` should be requiring an item param.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by Nantawat-Poothong — APPROVED** [review]
LGTM, make sure to get verified before merge. 😆

**Comment by Nantawat-Poothong** [comment]
> LGTM, make sure to get verified before merge. 😆

Oh I see, it's not in the JIRA board 🤔

**Comment by wsuwt** [comment]
@bualoy-napat  Can you quickly skim through this and https://github.com/Refinitiv/refinitiv-ui/pull/998

**Comment by bualoy-napat** [comment]
@wsuwt  LGTM!

**Pull request merged**
