### PR TITLE
Revert "feat(collapse): support screen reader"

### PR DESCRIPTION
**Pull request by TremayneChrist**
Reverts Refinitiv/refinitiv-ui#161

@Sakchai-Refinitiv this should be reviewed properly by members of the team with deeper accessibility knowledge.

### CODE REVIEW

**Comment by Sakchai-Refinitiv** [comment]
Hi Trem, I understand you about controlling the quality but if you want a team member who has accessibility knowledge to review all PR in this sprint, I think we will not close many cards because I have @wsuwt only in Bangkok Team who has deep accessibility knowledge and He might not bandwidth to review all of accessibility PR.

**Comment by TremayneChrist** [comment]
Quality is of upmost importance. We should not merge without a solid review of code. Forcing this to push tickets through a sprint is not justified.

**Comment by Sakchai-Refinitiv** [comment]
I agree with you, no problem, the product quality should come first.

**Comment by TremayneChrist** [comment]
We'll revert this today and you can restore your old branch and submnit a new new PR for review.

**Review by goremikins — APPROVED** [review]

**Comment by dtanp-rft** [comment]
@Sakchai-Refinitiv Please recreate https://github.com/Refinitiv/refinitiv-ui/pull/161 back again and we can put in scope of next sprint for deeper review.

**Comment by Sakchai-Refinitiv** [comment]
I have created a new one https://github.com/Refinitiv/refinitiv-ui/pull/189

**Pull request merged**
