### PR TITLE
fix(list): `selectItem()` should always require a param

### PR DESCRIPTION
**Pull request by wsuwt**
## Description

`selectItem()` should be requiring an item param.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by Nantawat-Poothong — DISMISSED** [review]
LGTM

**Comment by Nantawat-Poothong** [comment]
I have a question, isn't it will break backward compatible?

**Comment by wsuwt** [comment]
> I have a question, isn't it will break backward compatible?

Yes, it's possible. Though, I can't imagine why would someone use `selectItem()` without item as a parameter. This would always return `false` which is the reason I think this is meant to be bug fix rather than breaking features.

**Comment by Nantawat-Poothong** [comment]
> > I have a question, isn't it will break backward compatible?
> 
> Yes, it's possible. Though, I can't imagine why would someone use `selectItem()` without item as a parameter. This would always return `false` which is the reason I think this is meant to be bug fix rather than breaking features.

I see, I digged deep down to see the reason of this optional parameter item, seems like this 3 years code was invented by inattention code style not a feature.

**Review by Nantawat-Poothong — APPROVED** [review]
LGTM

**Pull request merged**
