### PR TITLE
fix(datetime-picker): allow user to clear invalid value in input

### PR DESCRIPTION
**Pull request by bualoy-napat**
## Description

To allow user to clear invalid input, we need to accept empty string for `value` and empty array for `values` to be assigned when current input is not valid.

Fixes # (issue) 
[ELF-1715](https://jira.refinitiv.com/browse/ELF-1715)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by Nantawat-Poothong — CHANGES_REQUESTED** [review]
I think the `error` state should be false after resetting the value

**Comment by bualoy-napat** [comment]
> I think the `error` state should be false after resetting the value

Good point! I will add code to vaildate the input again in order to reset `error` state.

**Comment by Nantawat-Poothong** [comment]
How about this one? just accept an empty array and go with the flow.
```typescript
  public set values(values: string[]) {
    const oldValues = this._values;
    if (String(oldValues) !== String(values) || !values.length) {
      this._values = values;
      this.valuesToSegments();
      this.requestUpdate('_values', oldValues); /* segments are populated in update */
    }
  }
```

**Comment by bualoy-napat** [comment]
> How about this one? just accept an empty array and go with the flow.
> 
> ```ts
>   public set values(values: string[]) {
>     const oldValues = this._values;
>     if (String(oldValues) !== String(values) || !values.length) {
>       this._values = values;
>       this.valuesToSegments();
>       this.requestUpdate('_values', oldValues); /* segments are populated in update */
>     }
>   }
> ```

To my mind, I also thought to accept empty array in that condition. But it would be better to split off the code in order to make it easy to understand.

**Comment by Nantawat-Poothong** [comment]
> To my mind, I also thought to accept empty array in that condition. But it would be better to split off the code in order to make it easy to understand.

I don't think so,  Due to setting `this.inputValues = [];`  I think splitting off the code like this will disrupt a normal flow and won't align with normal updating value flow. it may lead to another problem in further.

**Comment by bualoy-napat** [comment]
> > To my mind, I also thought to accept empty array in that condition. But it would be better to split off the code in order to make it easy to understand.
> 
> I don't think so, Due to setting `this.inputValues = [];` I think splitting off the code like this will disrupt a normal flow and won't align with normal updating value flow. it may lead to another problem in further.

I get it, I will update PR ASAP.

**Review by Nantawat-Poothong — APPROVED** [review]

**Comment by Nantawat-Poothong** [comment]
LGTM, wait to verified then you can merge to main branch.

**Pull request merged**
