### PR TITLE
ci: enable BrowserStack for nightly test

### PR DESCRIPTION
**Pull request by Sakchai-Refinitiv**
## Description

Enable `BrowserStack` for nightly test

## Type of change

Automate Testing

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Sakchai-Refinitiv** [comment]
@dtanp-rft  We have not run the nightly test for a while, it might have test cases failed which means we should fix it.

**Comment by Sakchai-Refinitiv** [comment]
> @dtanp-rft We have not run the nightly test for a while, it might have test cases failed which means we should fix it.

OK, But we should not leave it for long because the test cases might increase in Safari testing.

**Comment by dtanp-rft** [comment]
We should exclude Safari test from BrowserStack as it's still failed. Then we can merge nightly and at least, it runs on FireFox & Chrome latest + latest -1.

**Comment by Sakchai-Refinitiv** [comment]
> We should exclude Safari test from BrowserStack as it's still failed. Then we can merge nightly and at least, it runs on FireFox & Chrome latest + latest -1.

I have already updated it, the testing will run on three browsers Chrome, Firefox, and Edge in the version latest + latest -1.

**Review by dtanp-rft — APPROVED** [review]

**Pull request merged**
